services:
  blackflow:
    build: .
    image: harshoafk/blackflow:latest
    container_name: blackflow
    ports:
      - "80:80"
    volumes:
      - ./docs/example-configs/example.toml:/app/configs/config.toml:ro
    command: ["./blackflow", "./configs/config.toml"]
    depends_on:
      - auth1
      - auth2
      - api1
      - sessions1
      - sessions2

  auth1:
    image: python:3.12-alpine
    command: sh -c "echo auth1 > index.html && python -m http.server 8081"

  auth2:
    image: python:3.12-alpine
    command: sh -c "echo auth2 > index.html && python -m http.server 8082"

  api1:
    image: python:3.12-alpine
    command: sh -c "echo api1 > index.html && python -m http.server 8091"

  sessions1:
    image: python:3.12-alpine
    command: sh -c "echo sessions1 > index.html && python -m http.server 8101"

  sessions2:
    image: python:3.12-alpine
    command: sh -c "echo sessions2 > index.html && python -m http.server 8102"
