[server]
port = "80"

[server.rate_limit]
enabled = false
requests_per_second = 10
burst = 20

[server.routes."/auth"]
interval = "5s"
algorithm = "round_robin"
strip_prefix = true
backends = ["http://auth1:8081", "http://auth2:8082"]

[server.routes."/api"]
interval = "10s"
algorithm = "least_connection"
strip_prefix = true
backends = ["http://api1:8091"]

[server.routes."/sessions"]
interval = "10s"
algorithm = "ip_hash"
strip_prefix = true
backends = ["http://sessions1:8101", "http://sessions2:8102"]
