server:
    port: 80
    routes:
        /auth:
            interval: 5s
            algorithm: round_robin
            backends:
                - http://localhost:8081
                - http://localhost:8082
        /api:
            interval: 10s
            algorithm: least_connection
            backends:
                - http://localhost:8091
